import { User, Event, RegisteredEvent } from './types'

export const currentUser: User = {
  id: 'user-1',
  name: 'Alex Johnson',
  email: 'alex.johnson@email.com',
  phone: '+1 (555) 123-4567',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
  role: 'user',
  joinedDate: '2024-01-15',
  bio: 'Event enthusiast and tech lover',
  location: 'San Francisco, CA',
}

export const currentOrganizer: User = {
  id: 'org-1',
  name: 'Sarah Mitchell',
  email: 'sarah.mitchell@eventpro.com',
  phone: '+1 (555) 987-6543',
  avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
  role: 'organizer',
  joinedDate: '2023-06-20',
  bio: 'Professional event organizer with 5+ years of experience',
  location: 'New York, NY',
}

export const organizationName = 'EventPro Organization'

export const registeredEvents: RegisteredEvent[] = [
  {
    id: 'evt-1',
    title: 'Tech Conference 2025',
    description: 'Annual technology conference featuring the latest in AI and cloud computing',
    date: '2025-06-15',
    time: '09:00 AM',
    location: 'Moscone Center, San Francisco',
    category: 'Technology',
    capacity: 500,
    registeredCount: 423,
    image: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    status: 'upcoming',
    organizerId: 'org-1',
    organizerName: 'EventPro Organization',
    price: 149.99,
    registrationDate: '2025-03-10',
    ticketNumber: 'TK-2025-001',
  },
  {
    id: 'evt-2',
    title: 'Jazz Music Festival',
    description: 'A weekend of smooth jazz featuring international artists',
    date: '2025-05-20',
    time: '06:00 PM',
    location: 'Central Park, New York',
    category: 'Music',
    capacity: 2000,
    registeredCount: 1850,
    image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=400',
    status: 'upcoming',
    organizerId: 'org-2',
    organizerName: 'Music Events Inc',
    price: 75.0,
    registrationDate: '2025-02-28',
    ticketNumber: 'TK-2025-045',
  },
  {
    id: 'evt-3',
    title: 'Startup Pitch Night',
    description: 'Watch innovative startups pitch their ideas to top investors',
    date: '2025-04-10',
    time: '07:00 PM',
    location: 'Innovation Hub, Austin',
    category: 'Business',
    capacity: 150,
    registeredCount: 150,
    image: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=400',
    status: 'completed',
    organizerId: 'org-3',
    organizerName: 'Startup Network',
    price: 0,
    registrationDate: '2025-03-01',
    ticketNumber: 'TK-2025-102',
  },
  {
    id: 'evt-4',
    title: 'Digital Art Workshop',
    description: 'Learn digital illustration techniques from professional artists',
    date: '2025-07-22',
    time: '10:00 AM',
    location: 'Art Studio, Los Angeles',
    category: 'Art',
    capacity: 30,
    registeredCount: 18,
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?w=400',
    status: 'upcoming',
    organizerId: 'org-4',
    organizerName: 'Creative Arts Academy',
    price: 59.99,
    registrationDate: '2025-04-05',
    ticketNumber: 'TK-2025-178',
  },
]

export const organizerEvents: Event[] = [
  {
    id: 'org-evt-1',
    title: 'Summer Tech Bootcamp',
    description: 'Intensive 3-day bootcamp covering React, Node.js, and deployment strategies',
    date: '2025-08-10',
    time: '09:00 AM',
    location: 'Tech Hub, San Francisco',
    category: 'Technology',
    capacity: 100,
    registeredCount: 67,
    image: 'https://images.unsplash.com/photo-1517245386807-bb43f82c33c4?w=400',
    status: 'upcoming',
    organizerId: 'org-1',
    organizerName: 'EventPro Organization',
    price: 299.99,
  },
  {
    id: 'org-evt-2',
    title: 'Networking Mixer',
    description: 'Connect with industry professionals in a relaxed setting',
    date: '2025-05-05',
    time: '06:30 PM',
    location: 'Rooftop Lounge, New York',
    category: 'Networking',
    capacity: 80,
    registeredCount: 72,
    image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?w=400',
    status: 'upcoming',
    organizerId: 'org-1',
    organizerName: 'EventPro Organization',
    price: 25.0,
  },
  {
    id: 'org-evt-3',
    title: 'AI & Machine Learning Summit',
    description: 'Deep dive into the latest advancements in artificial intelligence',
    date: '2025-03-15',
    time: '08:00 AM',
    location: 'Convention Center, Seattle',
    category: 'Technology',
    capacity: 300,
    registeredCount: 298,
    image: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=400',
    status: 'completed',
    organizerId: 'org-1',
    organizerName: 'EventPro Organization',
    price: 199.99,
  },
]
